### ISSUE TITLE
Select all / none doesn't seem to work

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#100]
on e.g.
https://scrambler.cs.ox.ac.uk/entities/protocols/59/versions/v1/compare

Child of #68

**Comment by jonc125** [comment]
Confirmed this is still a bug with the latest master and cleared browser cache.

**Comment by mirams** [comment]
It's also showing models in the list to compare that are 'grey' or 'inapplicable'...

**Comment by jonc125** [comment]
I think that was always the case?

**Comment by mirams** [comment]
Hmmm, dunno. Would make sense to only do 'green','orange','red' ones. I think it might be showing 'blue' as well which could lead to confusion.
