### ISSUE TITLE
Upload models and protocols

### ISSUE THREAD

**Issue by helenst** [ModellingWebLab/WebLab#12]
Work out how to model models and protocols in a repository-backed way, such that a git repository is created for each model and protocol, and file versioning can be tracked through the repo rather than database structures. Set up a UI around this which will create those entities in the system and store them in the repository.

**Comment by helenst** [comment]
* allow deletion of entities
* apply permissions for entity creation and version creation.

**Comment by helenst** [comment]
@jonc125 I'm not sure when you're demoing this but I've fixed a couple of things in the upload and tied some of the UI together (so there should be some flow around creating a model and uploading files to a new version). It's all in the `model-entities` branch.

**Comment by jonc125** [comment]
Thanks for this Helen. I actually did the demo Friday morning so just described what you are working on now, but will take a look at the new bits tomorrow!

**Comment by jonc125** [comment]
Just seen the question above - yes, assuming you mean the local clone of the repo, it should be deleted if the entity is deleted.

**Comment by helenst** [comment]
I've created a PR #21 for the upload and version creation - there are a few outstanding items still on the list, which I've created separate issues for.
