### ISSUE TITLE
Add search function to metadata editor

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#121]
Can I put in a feature request for a search box above both trees? Ideally it'd have an autocomplete list hanging off, and selecting an item would then open the tree at the correct place

**Comment by jonc125** [comment]
This is now deployed on scrambler as part of #280 - see what you think!

**Comment by MichaelClerx** [comment]
Great, thanks!

**Comment by MichaelClerx** [comment]
Is there some one-liner we could do to e.g. replace spaces by wildcards in the previewed results?
To find L-type calcium current you need to type "l_type" on the left, "l-type" on the right, ideally "l type" would work in both?
