### ISSUE TITLE
Give more information when clicking on grey experiments

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#122]
For grey the new one just shows
<img width="894" alt="image" src="https://user-images.githubusercontent.com/858776/56041594-0169c380-5d31-11e9-9fa3-25b15281a5da.png"> 

The old Web Lab shows this:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/858776/56041577-f57e0180-5d30-11e9-903f-972acda49d60.png">

**Comment by jonc125** [comment]
You get a similar display if you click 'list all versions' in WL2. WL1 just doesn't allow you to view the version page for inapplicable experiments.
