### ISSUE TITLE
When creating, can model/protocol name be set on the same page as everything else?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#141]
Bit awkard now to upload several files, need to:

1. Open file browser, look at next file I'm going to upload
2. Type name of model/protocol, click create
3. Upload file (navigating to its location a 2nd time)

Would be much nicer to just

1. Upload file
2. Type name

**Comment by jonc125** [comment]
Not easily, due to the need to create the `Entity` object in the DB and corresponding git repo before being able to commit a new version to it. Changing this would also mean you'd have duplication between the 'create new entity' and 'create new version of existing entity' processes.

**Comment by MichaelClerx** [comment]
Not sure I follow. Does the view for creating a version depend on the `Entity` already existing? Otherwise I don't see why it couldn't just create the entity (if none exists) as part of creating the version

**Comment by jonc125** [comment]
It does, yes: see `EntityNewVersionView`

**Comment by jonc125** [comment]
I didn't say it was impossible, just not easy :)

**Comment by jonc125** [comment]
You also need to change the templates, forms, etc. to add the ability to set the entity name (and avoid displaying entity info in this case), change get_context_data, update/add tests, ...

**Comment by MichaelClerx** [comment]
Related to this, there's a message "This model has no versions" before I've created a model, and an option to "Re-run experiments involving the previous version of this model"

**Comment by jonc125** [comment]
> Related to this, there's a message "This model has no versions" before I've created a model

That was a message you asked for!

> and an option to "Re-run experiments involving the previous version of this model"

Ah, that I should probably fix :)

**Comment by MichaelClerx** [comment]
> >  Related to this, there's a message "This model has no versions" before I've created a model
>
> That was a message you asked for!

They're both related to the page not differentiating between a new model entity being created and a new version of an existing entity being created. It's a good message if you look at a model with no versions, but when creating a new model entity it doesn't make sense (even if you're technically creating a new version of a model you created seconds ago)

**Comment by jonc125** [comment]
OK, fixed these 2 issues as part of #180.
