### ISSUE TITLE
Can we get a "Create new model" on the experiments page?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#145]
The "Michael Clerx" button looks like I'd only use it for changing my profile picture, but is the core of the website...

**Comment by MichaelClerx** [comment]
Or more general, just permanently visible links to my models & protocols

**Comment by jonc125** [comment]
How would you like this to look?

**Comment by MichaelClerx** [comment]
![Screenshot from 2019-05-22 12-02-06](https://user-images.githubusercontent.com/517644/58170004-33ecd180-7c8a-11e9-811a-e5c9c53d03b4.png)

Something like this?
