### ISSUE TITLE
Version of experiment page is a bit unclear

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#149]
When I click the refresh button on a failed experiment, it's not terribly clear what's happening.

Also, leaving and returning to the page, I see the old error message. Hard to see if this is a the new version with the same error or the previous version.

Would probably be better to 

- Always jump to newest version, if user doesn't explicitly ask otherwise (even if the newest version hasn't completed yet)
- Add some red bar above the "Version 1" title, saying "You are viewing an older version of this experiment, to see the latest version click here"

**Comment by jonc125** [comment]
I'm not sure about the idea of jumping to the latest version, but #170 adds a (blue) bar informing you when there's a newer version, and #169 makes the notification when launching an experiment contain a link to the new version. Do these do enough between them?
