### ISSUE TITLE
Implement experiment matrix view

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#15]
With the ability to trigger new experiment runs just from this interface at present.

Child of #2.

**Comment by MichaelClerx** [comment]
At the moment, when I'm not logged in (so that the matrix is empty), the loading animation stays up, asking me to be patient

**Comment by jonc125** [comment]
Yeah, this is one of the known open issues in #51. It used to be you needed to be logged in to see the experiments page at all; I opened that up, but not (yet) the JSON view that the JS code calls.

**Comment by jonc125** [comment]
And now fixed :) Though about to be not-fixed again on scrambler as I switched the deployed branch.
