### ISSUE TITLE
Make names 'generic' Web Lab not Chaste/cardiac specific where possible

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#150]
Current settings contain:

```
# URL of Chaste backend
CHASTE_URL = os.environ.get('CHASTE_URL', 'http://localhost:5000/chaste')

# Password for Chaste backend
CHASTE_PASSWORD = os.environ.get('CHASTE_PASSWORD', 'YOUR_BACKEND_PASSWORD')

# Callback base URL
# This allows us to provide the Chaste backend with URLs that it can access
# (it may not be able to do so via the user-accessible URL)
CALLBACK_BASE_URL = os.environ.get('CALLBACK_BASE_URL', 'http://localhost:8000')
```

But isn't the front-end supposed to talk to a celery task queue @jonc125 ?

**Comment by jonc125** [comment]
It does, but via a web service API, not directly - so the task queue can be on a different host from the front-end. And the technologies are decoupled - recall the front-end used to be Java not Python.

**Comment by MichaelClerx** [comment]
So where it says "chaste", is that the path where the task queue is running then?

**Comment by jonc125** [comment]
The `CHASTE_URL` gives the full URL to the webservice. In the Ansible deployment it's set up by the fc-web-service role, and served via nginx & fcgiwrap.

**Comment by MichaelClerx** [comment]
Should we change this to e.g. `TASK_QUEUE_URL` then?

**Comment by jonc125** [comment]
Could do at some point, along with other references to Chaste. May be best to do wholesale when we finally replace pycml?

**Comment by MichaelClerx** [comment]
Maybe! I was also thinking along lines of having a generic web lab (not FC- / cardiac-specific) - so no variable names that reference stuff that goes on inside the task runners
