### ISSUE TITLE
Error messages hide compatibility info message

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#152]
Steps to reproduce:

1. Run an experiment with an incompatible model and protocol combination
2. Quickly click on the matrix again, to see the message that they're not compatible
3. Go back to the matrix view
4. Click again, now you see an error message, and the original information is gone

I liked the original information! And if there's multiple output / multiple errors we need to see them all

**Comment by jonc125** [comment]
When you say 'go back' do you mean with the back button in the browser? Probably the browser is caching the original version of the page, not the updated JS state.

**Comment by MichaelClerx** [comment]
Yeah just going back. But it doesn't matter if you refresh, the view of the experiment version changes from initial output to the most recent error

**Comment by jonc125** [comment]
Huh, that shouldn't happen! It might just be because the most recently merged PRs haven't yet been deployed on scrambler? Or is this on a dev setup?

**Comment by MichaelClerx** [comment]
It's on a dev setup

**Comment by MichaelClerx** [comment]
Can't reproduce, probably fine now after #169 :-)
