### ISSUE TITLE
Option to view uploaded file?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#154]
Not sure if this is possible at the moment, or if they only get actually uploaded when a version is created, but if they're already on the server would be nice to be able to see that I've got the correct file before clicking "Create"

**Comment by jonc125** [comment]
This wouldn't be easy to do, as they're not in the right part of the system to be viewed until the entity is created, they're only in the temporary uploads folder. And all the Javascript code for viewing things assumes you're in the context of an entity/dataset/etc.
