### ISSUE TITLE
Experiment version view: When do we see the blue "Running" bar?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#156]
I quite like it, but most of the time I see this instead:

> This experiment has not yet finished running, and so no result files are available. You can refresh the page to see if it has completed. 

I'm guessing that's a "pre-running" message then? The status indicator above says "Status: RUNNING" though, so a bit confused what's going on

**Comment by jonc125** [comment]
Ah, do you mean the separate notifications box overlaid at the top?

That appears if it's *launching* another experiment. You'll typically see it if you've created a new version and asked to re-run previous experiments.

**Comment by MichaelClerx** [comment]
No I mean the one on the experiment version page!

Seems like there's 

1. a pre-running stage where you get the text message (although the page says "status: RUNNING")
2. a running stage, where you no longer get the helpful text message, but you do see a blue bar that says running (status is still "RUNNING")

Is that correct? And if so, maybe we should show identical output in both states, or update the status  in 1 to something other than "RUNNING" ? Maybe "initialising" ?

**Comment by jonc125** [comment]
I'm confused now. The list of versions page, or the view of a single version?

Below are some different screenshots from my system.

Version list, queued experiment:
![Screen Shot 2019-05-20 at 13 24 08](https://user-images.githubusercontent.com/2032871/58021385-aaf75e00-7b02-11e9-9f13-7b8a833eea78.png)
---
Version list, running experiment:
![Screen Shot 2019-05-20 at 13 24 37](https://user-images.githubusercontent.com/2032871/58021384-aa5ec780-7b02-11e9-862f-2950bb1b64fa.png)
---
Version page, re-run submitted:
![Screen Shot 2019-05-20 at 13 23 45](https://user-images.githubusercontent.com/2032871/58021386-aaf75e00-7b02-11e9-9dff-a89e4fb2fea1.png)
---
Version page, queued experiment:
![Screen Shot 2019-05-20 at 13 22 54](https://user-images.githubusercontent.com/2032871/58021388-ab8ff480-7b02-11e9-9e6f-d773fad90724.png)
---
Version page, running experiment:
![Screen Shot 2019-05-20 at 13 23 12](https://user-images.githubusercontent.com/2032871/58021387-aaf75e00-7b02-11e9-8220-40af2d8472a2.png)
---

I can't think of any other appearance that might occur.

**Comment by MichaelClerx** [comment]
Managed to catch one!

![Screenshot from 2019-05-20 16-13-46](https://user-images.githubusercontent.com/517644/58032411-75f70580-7b1a-11e9-870b-7d703b11fd3e.png)

Looks like it's actually Failed, at this point

I quite like the blue bar anyway. Maybe the normal running screen should have it too?
