### ISSUE TITLE
Some feedback during experiment run?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#157]
At the moment, the `fc-runner` hands off to a subprocess to do the interesting stuff.

As far as I can see, from that moment until the time the subprocess is done there's no communication or communication channel with the front-end?

Would be nice to be able to get some kind of feedback to the user at this stage

**Comment by jonc125** [comment]
That's correct, yes. Doing better would require the fc process (or whatever experiment runner) to be able to call back to the front-end with more regular pings.
