### ISSUE TITLE
Delete version of protocol

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#159]
Don't see an option to do this

**Comment by jonc125** [comment]
Indeed, you can't, because it means messing with git history, which we decided was a bad idea.

**Comment by MichaelClerx** [comment]
What if it's only the newest version you want to remove? Will you have to remember what you changed and then undo it yourself? Because that kinda defeats the purpose of having version control

**Comment by jonc125** [comment]
Duplicate of #39
