### ISSUE TITLE
Changing entity description?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#168]
What if users want to e.g. fix typos in descriptions?
At the moment this is not possible, as the interface recognises the files haven't changed, so no commit can be made

**Comment by jonc125** [comment]
What do you mean by descriptions? You can update the readme file in a new commit. But the commit message is immutable - that's a git feature.

**Comment by MichaelClerx** [comment]
So we'd have to work around that, e.g. by touching one of the files?

**Comment by jonc125** [comment]
If you wanted a new commit message, yes.

**Comment by MichaelClerx** [comment]
We should think about doing this automatically if the user changes the "description" field but nothing else. Or just stop displaying the commit messages altogether? (#155 )
If we do keep them, might be worth auto-generating suggested messages (like github does if you change a file via the web interface)
