### ISSUE TITLE
Register page should be invisible to logged in user

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#177]
Should just redirect to home / landing-page

At the moment, you can get this situation:

1. Click "register" instead of "log in" by mistake
2. Click "Log in"
3. Log in
4. You now get redirected to the last page before you logged in --> The registration page

Bit confusing unless you spot that you're actually logged in now!

**Comment by sroderick-g5sro** [comment]
I was under the impression that this was governed by LOGIN_REDIRECT_URL in settings.py but this is currently set to "/" so not sure how its doing the redirect to previous page.

**Comment by jonc125** [comment]
It uses Django's built-in [LoginView](https://docs.djangoproject.com/en/1.11/topics/auth/default/#django.contrib.auth.views.LoginView) which redirects to the page in the `next=` parameter if given. Changing that behaviour for one specific redirect doesn't look easy (we'd probably have to subclass the view).

It might be easier to edit the `registration/register.html` template to add an `{% if user.is_authenticated %}` section into the `<head>` that uses `<meta http-equiv="refresh" content="0; url=/" />` to redirect again! (Which would need an extension to `base.html` so you can add content into the `head` section of the page.)
