### ISSUE TITLE
Add histogram visualisations

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#19]
Based on Aidan's code in the existing Web Lab - https://bitbucket.org/joncooper/fcweb/branch/cardiac-fitting

**Comment by jonc125** [comment]
(There's also the electrochemistry branch at https://bitbucket.org/joncooper/fcweb/branch/echem, but I think the plotting was copied from that to the cardiac branch.)

**Comment by jonc125** [comment]
Changes for this can be seen at https://github.com/ModellingWebLab/fcweb/compare/cardiac-fitting

**Comment by MichaelClerx** [comment]
Not priority for the workshop I think, where we'll focus on optimisation rather than MCMC!

**Comment by jonc125** [comment]
What output visualisation is needed for the optimisations for the workshop?

**Comment by MichaelClerx** [comment]
If it's really just optimisation then no output visualisation is needed, just the ability to show (print or write to file) the final parameters and possibly the error. 

@mirams what do you think? Should we allow at least a "bad" (short, one chain) MCMC run, to stick closer to the theme of UQ?

**Comment by mirams** [comment]
Yeah it would appeal to the audience to see an MCMC histogram too, maybe put it at the top of the 'nice to have but not essential' list?

**Comment by jonc125** [comment]
Done in #173.
