### ISSUE TITLE
Upgrade to Django-2

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/WebLab#195]
I accidentally had django-2 installed and found that code is not compatible. We might want to look into this at some point.

Edit: [2.2 is now the earliest supported version](https://www.djangoproject.com/download/#supported-versions) so we'd better upgrade soon! That's also the only current LTS version.

Using `PYTHONWARNINGS=always pytest --capture=no` gives an indication of things to change in advance. We have 2 areas we currently use that are unsupported in 2.0:
```
/Users/jonc/projects/WebLab/WebLab/weblab/core/models.py:4: RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.
/Users/jonc/projects/WebLab/WebLab/weblab/core/models.py:31: RemovedInDjango20Warning: on_delete will be a required arg for ForeignKey in Django 2.0. Set it to models.CASCADE on models and in existing migrations if you want to maintain the current default behavior. See https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey.on_delete
```
The latter comes up in many places.

The [v2.2 changes](https://docs.djangoproject.com/en/3.1/releases/2.2/#backwards-incompatible-changes-in-2-2) don't look that scary. Likewise [v2.1](https://docs.djangoproject.com/en/3.1/releases/2.1/#backwards-incompatible-changes-in-2-1).

https://docs.djangoproject.com/en/3.1/releases/2.2/#permissions-for-proxy-models might simplify our collaborators on fitting specs issue!

To do the upgrade, we need to change the versions specified in `requirements/base.in` and run `make` within the requirements folder, then `pip install -r requirements/dev.txt`.

**Comment by jonc125** [comment]
When we do upgrade to Django >= 2.1, we can improve `core/models.py` with:
```python
    @property
    def collaborators(self):
        """
        All users who have specifically been permitted to collaborate on this object

        :return list of `User` objects
        """
        return get_users_with_perms(self, only_with_perms_in=['edit_entity']).all()
```

**Comment by jonc125** [comment]
Harry has recently done a similar upgrade for Dashboard. The model-mommy dependency we use in testing might be a bit more complex, but there's a helper script. See https://github.com/UCL-RITS/RSD-Dashboard/commit/35829595280677512719faea55ffeabe757a93d5 and https://github.com/UCL-RITS/RSD-Dashboard/commit/4c196af1da06d6ee99a18fcb87099c4c7bb1497f
