### ISSUE TITLE
Fix uploading and viewing datasets

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/WebLab#199]
When looking into writing tests for datasets with files I came across the following issues:

1. I have created and uploaded a zip file for a dataset but later clicking on the link for this dataset gives me the addfiles page - and an html exception for this page. 

2. I have created and uploaded a zip file for a dataset but later clicking on the link for this dataset gives me the details page but with no files listed but it does have 'Files in this dataset' and the download button.

3. If I manually go to the dataset details page it does not show 'Files in this dataset' and the download button.

I cannot replicate this in master as my change of experimentaldataset name to just dataset everywhere in my add-tests-for-datasets branch messes with the postgres and so matser doesnt work with my db !! "relation "datasets_experimentaldataset" does not exist" since in my version it is datasets_dataset.

So do I try and fix the issues above (well yes they need fixing) or possibly revert my change of name (although can't see why that would be the issue!)

**Comment by skeating** [comment]
Note to self: 
#1 happens for my ds2/dsnew
#2 happens for my ds1

**Comment by jonc125** [comment]
Can this be closed now we merged #200 ?

**Comment by skeating** [comment]
Yes. This was a side effect of my attempts to create datasets with files. The issues were non issues
