### ISSUE TITLE
List of queued or running experiments

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#207]
Quite often I'll upload a model, start a batch of experiments, and then find an issue with the model.
This renders all running experiments with that version useless, as I'll have to add a new version which will replace the old version in the matrix.

It would be nice to have an option to:
- Kill all my simulations for a given model version (or at least unqueue queueueued ones)
- Kill all my simulations in general, ideally via a list of running and queued (but not finished!) experiments (a bit like windows' process manager)

This would save me a lot of time

**Comment by jonc125** [comment]
See also #39.

**Comment by jonc125** [comment]
Is the time saving enough that it's worth prioritising above say progress on fitting experiments?

It could make a good self-contained early task for @d20gdx

**Comment by MichaelClerx** [comment]
I imagine the ability to terminate/unschedule a fitting task will be very useful when debugging fitting!

**Comment by sroderick-g5sro** [comment]
I have been considering how this functionality might be incorporate into the current front end. One idea Jonathan and myself discussed was having a new option in the "admin" drop down menu (under username), This might have text such as "Manage running experiments". This then takes the user to a screen which lists all experiements (that they are the owner of) grouped by queued and running. I would then suggest using check boxes to select which ones to kill.  A checkbox at the group level would select all queued or all running. There would then be a confirmation dialog to confirm termination. @MichaelClerx  please can you advise if this sounds ok.

**Comment by sroderick-g5sro** [comment]
a related issue is how we want to notify users, e.g. do we "spam" them with emails saying each individual experiment has been cancelled. Or maybe a single email to confirm at then end.

**Comment by MichaelClerx** [comment]
Yeah that sounds fine!

I imagine some experiments won't want to die for a while, so maybe individual emails?

**Comment by sroderick-g5sro** [comment]
I have submitted a pull request for initial development of this enhancement
