### ISSUE TITLE
Multi-line labels?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#216]
My matrix has gone very ugly:

![Screenshot from 2019-11-13 15-28-41](https://user-images.githubusercontent.com/517644/68777979-67e9f380-062a-11ea-9807-5967ccd9c78c.png)

The increased vertical spacing makes it harder to scan over my list of models

**Comment by jonc125** [comment]
Which labels do you want to be multi-line?

**Comment by MichaelClerx** [comment]
None of them, I think. The multi-line ones on the left make the matrix harder to navigate
