### ISSUE TITLE
Copying & sharing protocols from WL1

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#224]
I'd like to copy Ken's old protocols (about 20 of them!) to WL2, and make it so that Aditi can see them too.

What I've done so far:
- Downloaded Ken's protocols from WL1 (can see them as admin)
- Uploaded protocols to WL2 under my own account
- Added Aditi & Myself as collaborator to each protocol via the front-end
- Set Ken as the owner of each protocol via the back-end

Now when I log in I can see Ken's experiments under "visible experiments" but can I check that's not because I'm admin?

**Comment by MichaelClerx** [comment]
@jonc125 says: In WL2 admins don't get special privs to see everything. At least not in the front-end, running expts, etc

**Comment by MichaelClerx** [comment]
OK so I can see them in the matrix now, but I get a 500 server error if I click the protocol name

**Comment by jonc125** [comment]
I'm seeing `NoSuchPathError` in the logs, which seems a bit odd!

Actually, no it isn't - the storage is per-user, so when you changed the owner it changed where it expected to find the protocol, without actually moving the repo.

**Comment by MichaelClerx** [comment]
OK. So how can I fix this? And how can we implement owner changes in the future?

**Comment by jonc125** [comment]
I can manually move the repos later I expect. If it’s a feature you want, then we’d better create an issue for that. Or you can keep yourself as the owner and just share with Ken et al, and they should be able to add new versions themselves.

**Comment by MichaelClerx** [comment]
In this case it'd be best to have Ken own them. I'll create an issue for transferring ownership!

**Comment by jonc125** [comment]
Repos were moved manually.
