### ISSUE TITLE
Add option to transfer ownership of entities

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#225]
Very useful when helping people with web lab stuff, and transferring entities from old to new

**Comment by jonc125** [comment]
Changing the owner in the database is easy, but this also needs to move files around on the filesystem so they live under the new owner's folder.

Similarly to the add collaborators view, you'd need to enter the email address of the new owner, and the view would need to check they actually exist as a user. We don't use a drop-down list as normal users shouldn't be able to see a list of all users!

**Comment by jonc125** [comment]
Done in #294.
