### ISSUE TITLE
Rerun experiments re-runs on all previous versions of model/protocol instead of just latest

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#230]
When uploading a new version of a model/protocol the 're-run experiments using this version' is really nice, but it is re-running all the old protocols/models and not just the latest one, which is probably what we want the default behaviour to be.

**Comment by jonc125** [comment]
It already only re-runs experiments that involved the immediate parent of the new version, is that not what you mean?

Or is it that if you upload a new version of a protocol say, and the previous version was run with 3 versions of the same model, you'll get 3 new experiments submitted, whereas you want only 1?

**Comment by mirams** [comment]
Yeah, the second. So if there are 10 previous versions of a model and I upload a new protocol, all 10 will run instead of just most recent version of a model.

**Comment by jonc125** [comment]
Hmm, it doesn't look easy with the current DB structure to ensure you get just the latest version of the entity. If there are multiple versions however, it's easy to get the one for which the `Experiment` was created most recently, which is probably going to be the same almost all the time I guess? Would that be reasonable?

**Comment by mirams** [comment]
Doesn't (e.g.) this view always give you a list of them:
https://scrambler.cs.ox.ac.uk/entities/protocols/6/versions/conductance_can_be_dervied_quantity/compare

**Comment by mirams** [comment]
Oh, no it doesn't! It's listing v2 of Tomek when others are available! That's not ideal...

![image](https://user-images.githubusercontent.com/858776/72269360-5d90a980-361b-11ea-8b8f-998b694475e8.png)

**Comment by jonc125** [comment]
Yes, you can get a list of all versions easily enough. It's just that in the place where it's finding experiments to run, it's looking at a table from which it's not easy to get to that list. So it would take a more substantial change (and thinking!) to do it. And possibly be slightly slower, though that shouldn't be too significant.

**Comment by jonc125** [comment]
It will only re-run experiments that the user submitting the new version can see, incidentally.

**Comment by jonc125** [comment]
This might be easier to change now #250 is done, actually.

**Comment by jonc125** [comment]
The simplest logic to implement, and possibly what users most expect, isn't strictly speaking to re-run experiments run with the immediately preceding version. Instead, we could:
1. Find all experiments run with the entity for which we're adding a new version (suppose it's a model for the sake of argument; if it's a protocol being updated the logic is analogous).
2. Get the list of corresponding protocol IDs.
3. We now know both our model ID, and all protocols that have previously had any version run on any version of this model.
4. Run our new model version under the latest (visible) version of all those protocols.

Does that seem reasonable @mirams ?

If so, we might want to update the checkbox description, although it could get quite long! Currently it's "Re-run experiments involving the previous version of this model". We could say "Re-run the latest versions of protocols previously run on this model" or somesuch? Or just keep as is?

Implementing the change would need to happen in `entities.processing.record_experiments_to_run`. For the logic above, we could do something like:
```python
if entity.other_type == entity.ENTITY_TYPE_MODEL:
    other_model = ModelEntity
else:
    other_model = ProtocolEntity
search_args = {
    entity.other_type + '_experiments__' + entity.entity_type: entity,
}
other_entities = other_model.objects.visible_to_user(user).filter(**search_args)
for other_entity in other_entities:
    # Look for latest visible version
    for other_version in other_entity.cachedentity.versions.reverse():
        if other_entity.is_version_visible_to_user(other_version.sha, user):
            # Record the new experiment to run
            kwargs = {
                'submitter': user,
                entity.other_type: other_entity,
                other_entity + '_version': other_version.sha,
            }
            kwargs.update(new_version_kwargs)
            PlannedExperiment.objects.get_or_create(**kwargs)
            break
```

**Comment by mirams** [comment]
Yeah, I think so. 

I'm pretty sure the old WL did this sort of thing, and had a button to select just the latest version or all versions e.g. under Compare Models on https://travis.cs.ox.ac.uk/FunctionalCuration/protocol/INaIVCurve/10/withvoltageclampplots/112

**Comment by jonc125** [comment]
We do have that kind of view already, e.g. https://scrambler.cs.ox.ac.uk/entities/protocols/2/versions/v1/compare

For re-running, do we want the option to re-run with *every* earlier combination? Or only the latest visible as described above?

**Comment by mirams** [comment]
> We do have that kind of view already, e.g. https://scrambler.cs.ox.ac.uk/entities/protocols/2/versions/v1/compare

Yeah, as per the screenshots above, a bit of confusion as that view lists the latest versions that have been run, and doesn't point out (I don't think) that a later version of the models are available when you are doing the comparison.

> For re-running, do we want the option to re-run with _every_ earlier combination? Or only the latest visible as described above?

Probably be good to have both, when you click 'Run Experiments' for a given protocol it does bring up all the model versions with just the latest checked as default (I think), this is probably what we want the 'Re-run' button to do for a new version of a protocol too.
