### ISSUE TITLE
Tidy up output of metadata editor

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#243]
A couple of things that would be nice.

1. At the moment WebLab metadata-annotated files look like this:

![image](https://user-images.githubusercontent.com/858776/73082529-8f2e2e00-3ec1-11ea-8ff3-1a0344e846a5.png)

with all the RDF tags on one line. Whereas COR exports things that look like:
![image](https://user-images.githubusercontent.com/858776/73082645-c69cda80-3ec1-11ea-8011-09e9c0bb230f.png)
 which is much nicer with some formatting and indentation etc.

2. Also note how `gedit` picked up the highlighting for the COR exported file, but not ours, because the COR one has 
`<?xml version='1.0' encoding='UTF-8'?>` as the top line of the file, but we just start with the `<model>` tag.

**Comment by jonc125** [comment]
Hmm, this might not be straightforward: the [standard javascript API](https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer/serializeToString) we're using to serialize doesn't take any formatting options! So we'd need to look into a third-party library for doing it, or write something ourselves. A quick & dirty solution might be to stick the XML header at the start of the string, and prepend all occurrences of `<rdf:`, `</rdf:`, and `<bqbiol:` with a newline...

**Comment by mirams** [comment]
Quick and dirty would be a good start anyway!
