### ISSUE TITLE
No sharing (collaborators) functionality for datasets

### ISSUE THREAD

**Issue by sroderick-g5sro** [ModellingWebLab/WebLab#247]
Other entities (including fitting specs) have a manage collaborators functionality that allows sharing. This has not been implemented for datasets. 

Background:
from a coding perspective, datasets should inherit the add_collaborators method but the guardian library throws a permissions issue, eg, 

```
        if not num:
            raise self.model.DoesNotExist(
                "%s matching query does not exist." %
>               self.model._meta.object_name
            )
E           django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.
```

a new version of this library exists but required Django version 2

**Comment by jonc125** [comment]
I think I've figured out how to do the permissions properly - see my 2 commits on the PR. Which means (apart from fixing the tests that the change to `is_editable_by` broke!) that the remaining steps are the UI for adding dataset collaborators.

It should be possible to use `EntityCollaboratorForm` and `EntityCollaboratorFormSet` directly, so no need to write a new form. `datasets.views.py` will need a view inheriting from `EntityCollaboratorsView` that changes the `template_name` field and `get_context_data` (to remove the `type` kwarg). If the new view is accessed via a URL named `datasets:entity_collaborators` then nothing else should need changing in the code. Just a new template added based on the entity collaborator one but adapted for datasets.

I'd suggest a bit of experimentation with the feature live to see if any oddities arise (check a test user you share with can see the dataset, etc.) and review the collaboration tests for entities to see which ones make sense to replicate for datasets.

**Comment by sroderick-g5sro** [comment]
When I click on the Manage Collaborators link I get the following error message. I dont understand why because it refers to a link in the dataset header.

![image](https://user-images.githubusercontent.com/3098326/100448616-77f43a00-30aa-11eb-9304-bdbeee81d7b0.png)

**Comment by jonc125** [comment]
Looks like that's because `dataset` isn't provided in the context for the template, and the header expects it. So `DatasetCollaboratorsView` probably needs its own `get_context_data` that sets that as well as calling the superclass method.

**Comment by sroderick-g5sro** [comment]
thanks Jonathan, I'm not clear now I set the dataset and call the superclass method. I think you mention before not using kwargs so this is as far as I got

```
    def get_context_data(self):
        dataset = self.get_object()
        return super().get_context_data()
```

**Comment by jonc125** [comment]
Follow an analogous approach to `EntityCollaboratorsView` - using `kwargs` is appropriate here as that is the interface Django expects the method to have.
