### ISSUE TITLE
Allow all users to view (but not edit) the annotations of any model they can see

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#248]
Now the annotations button is simply not shown. It'd be nicer if the users could still see if the model has the right annotations without having to look at the CellML code.

**Comment by jonc125** [comment]
Currently in `editMetadata.js` we have
```js
    if (!$('#entityversion').data('can-edit'))
        return false;
```
in the `canRead` function.

We could remove it from there and instead use the logic to guard filling `otherContent` in the constructor (which contains the form fields for saving a new version). We should probably also guard the `li.draggable` and `li.droppable` calls.
