### ISSUE TITLE
Allow annotation with non-oxmeta terms

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#255]
The logic to pull all terms used by protocols will reveal non-oxmeta terms that could be useful. The annotation tool should include a section containing these so that they can be added to models.

**Comment by jonc125** [comment]
Thinking through what's needed for this...

We probably want a new category `oxmeta:CustomAnnotations` in the oxmeta ontology to place custom annotations within.

Checking if an annotation isn't in our ontology, and adding it as an available annotation if not; this will need to be done in the `filtersLoaded` function:
```js
var oxmeta_uri = self.rdf.prefix('oxmeta'),
    relative = oxmeta_uri.relative(term);
if (relative == term)
{
    // Make this non-oxmeta term recognised as an annotation in the custom category
    self.rdf.add(term + ' a oxmeta:Annotation');
    self.rdf.add(term + ' a oxmeta:CustomAnnotations');
}
```

If `self.mainAnnotDiv` is already filled then `filtersLoaded` will need to re-populate it:
```js
if (self.mainAnnotDiv.children('ul').length > 0)
{
    self.mainAnnotDiv.empty();
    self.terms = [];
    self.fillCategoryList(self.mainAnnotDiv, self.rdf.where('?ann a oxmeta:Category'));
}
```

**Comment by MichaelClerx** [comment]
Not sure I agree with this logic!
For example, wouldn't want to see any old terms that other people use in my list, and maybe not even ones I used a few years ago. And how do I add new terms?

**Comment by jonc125** [comment]
It only shows those appearing in protocols you can see (so you won't see other people's private terms). And you can filter the annotations shown by protocol, so if you're annotating a model to work with a particular (set of) protocols you can show just the terms needed.
