### ISSUE TITLE
Allow an entity version to be downloaded as a COMBINE archive

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#26]
This is the 'Download archive of all files' functionality in the existing site.

**Comment by MichaelClerx** [comment]
Can we start by just downloading a zip of the repo?
I want both options: Zip for people who just want the files, Combine for futuristic cool stuff

**Comment by jonc125** [comment]
A COMBINE archive *is* a zip file - just with some specific metadata files included within it, and optionally a custom extension.

**Comment by MichaelClerx** [comment]
Still!

**Comment by jonc125** [comment]
So, yes, we could start with just a zip download, then add the manifest as a later step :)

And if as part of #23 the manifest is a file in the repo anyway, a zip download will automatically be a combine archive too...

**Comment by MichaelClerx** [comment]
I do like that part of the idea! As long as we can make it clear to users

**Comment by jonc125** [comment]
Blocked by #30.

**Comment by helenst** [comment]
It's mostly implemented as part of the experiment runner integration, so entities could be downloaded by the runner. However, I'm not sure it's linked from the web interface yet.

**Comment by jonc125** [comment]
Ah yes, it's linked for the experiment view but not for models or protocols.

**Comment by jonc125** [comment]
Now fixed in #92 while working on #91.
