### ISSUE TITLE
Versions of experiments

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#267]
The experiments have versions now, which is a bit weird? If nothing is broken, every version should be the same. What I would much prefer instead of "list versions" is "list protocol versions" and "list model versions", so that I can see how the results compare to previous models/protocols

**Comment by jonc125** [comment]
Versions can easily differ if the underlying software has been updated in any way...

Also sometimes the first run just hit an unexpected error (network timeout or whatever) so had no results.

**Comment by jonc125** [comment]
But adding extra links to the existing views could be done.

**Comment by jonc125** [comment]
@MichaelClerx for instance, we could link to [this matrix](https://scrambler.cs.ox.ac.uk/experiments/models/11/versions/*/protocols/2/versions/*) from a [single experiment view](https://scrambler.cs.ox.ac.uk/experiments/26419/versions/26811/outputs_All_state_variables_gnuplot_data.csv/displayPlotFlot). But what would we call it and where would we put the link? Alongside 'list all versions' but called 'compare results from other model/protocol versions'?

**Comment by MichaelClerx** [comment]
That sounds good! Or even just "see" instead of "compare" !

**Comment by jonc125** [comment]
So I think we'd want a template tag which has similar functionality to `url_version_comparison_matrix` in `experiments.py` but that takes both a model and a protocol as arguments (and so is a `simple_tag` rather than a `filter`). And you'd need to use that to construct a link within `experimentversion_detail.html`.
