### ISSUE TITLE
Add UI to link a dataset and protocol

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#274]
This is to set up the mapping between dataset columns and protocol outputs (and inputs).

Initially this will be triggered on creation of a dataset, as the next step after adding files to it. But we could also use it to create a new link between already an existing protocol & dataset, e.g. once datasets are not tied to a single protocol. And we'll need it to be used for existing already-linked datasets to set up the mapping.

- [ ] Enhance the protocol analysis back-end task so it tells the front-end what the (inputs and) outputs are, and their units.
    - [x] Just outputs is enough for a first pass.
    - [x] On deployment of new back-end, re-analyse existing protocol versions.
    - [ ] Doing inputs will require adding info on their units, somewhere.
- [x] Cache that info in the DB, similarly to the interface a protocol expects from models.
- [x] Add a model for capturing the mapping from dataset columns to protocol inputs/outputs, probably with fields `dataset`, `column_name`, `column_units`, `protocol_version`, `protocol_in_out_put`, `protocol_units`, `is_output` or similar.
    - Actually, the last 3 can be replaced by a foreign key to `repocache.ProtocolIoputs`
- [x] Add a view to fill the mapping in, which gives essentially a row for each dataset column, with a text field allowing the units to be entered, and a drop-down selecting the protocol input/output (or not mapped)
    - [x] Need to consider how we want to allow the units to be specified. I suggest a text string that's parse-able by [pint](https://pint.readthedocs.io/).
    - [x] Jonathan to give examples of pint definition strings and the parsing process.

**Comment by jonc125** [comment]
Quickstart tips for [pint unit processing](https://pint.readthedocs.io/en/stable/tutorial.html#tutorial):

```python
from pint import UnitRegistry
ureg = UnitRegistry()

quantity = ureg(unit_string)  # Can raise pint.UndefinedUnitError, pint.DefinitionSyntaxError - should give a friendly form error for each type separately I think

display_for_templates = '{:H}'.format(quantity)
```

**Comment by jonc125** [comment]
I'm thinking as part of this issue it might actually make sense to make the `Dataset`-`Protocol` link a many-to-many relation. So a `Dataset` wouldn't *need* a protocol link, and could have more than one (and a `Protocol` could be related to many `Dataset`s as currently). Creating a new `Dataset` would not specify a `Protocol`, but instead when viewing a dataset (after file upload) there would be a "Link to protocol" button (hover text: "Associate this dataset with a protocol representing the experimental scenario"). And similarly when viewing a protocol we could have a "Link to dataset" button (hover: "Associate this protocol with experimental data produced under an equivalent scenario").

Does that sound good @mirams ?

**Comment by mirams** [comment]
I'm a bit wary of adding complication when the main thing you want to do with a dataset on the WL is 'run the experiment needed to reproduce this' and then there will turn out to be more than one, which seems odd?

**Comment by jonc125** [comment]
Fair enough, let's stick with a single protocol per dataset for now then, and potentially expand later.

**Comment by helenst** [comment]
Tasks:
- [ ] Create model for column mappings
- [ ] Add view for creating mappings
  - [ ] Load column names from dataset
  - [ ] Load available inputs/outputs based on selected protocol version
  - [ ] Validate column units field
- [ ] Link from existing dataset
- [ ] Show form after dataset creation

**Comment by helenst** [comment]
I guess `protocol_version` doesn't need to be stored directly if it's already on a foreign key from `ProtocolIoputs`

**Comment by jonc125** [comment]
Specifying column units without a mapping is fine: that just provides useful metadata for a column that's present in the data but not actually used for fitting.

Ideally I think we'd want units specified for all columns, so arguably we could say it's an error if one is left out at all @mirams @MichaelClerx ?  Or might the units be unknown in some cases?

If a mapping to a protocol ioput is given then I think we definitely want to require units.

I agree for the case if neither is done.

**Comment by mirams** [comment]
Probably OK to ignore columns that aren't associated with protocol inputs or outputs and not worry if they are missing units. I suspect if we insist on them we'll get people dragging and dropping "dimensionless", or nonsense, and wrong annotations are probably worse than missing annotations!

**Comment by helenst** [comment]
OK - just to make sure I've got that straight, I'll make protocol ioputs optional. If a protocol ioput is selected, units must be given. But it's OK if there's neither. Have I understood that right?

**Comment by helenst** [comment]
What should be the logic for determining where the column names come from? In the dataset currently in the system, there is a single CSV file so it's fairly clear - but how complex can it be? Might there be multiple CSV files or other non-csv files?

**Comment by jonc125** [comment]
Certainly only ever from CSV files, and I think the back-end can only cope with a single 'main' CSV file at present so we could start with that. Extending to pick up any CSV file shouldn't be difficult if that's wanted @mirams ?

**Comment by mirams** [comment]
Yeah, happy with 1 csv file to start with. 

I suppose more complicated use cases might have more than one but we can cross that bridge when we come to it unless it is easier to think about now?

**Comment by jonc125** [comment]
Created https://github.com/ModellingWebLab/weblab-fc/issues/228 for the remaining tasks on this issue.
