### ISSUE TITLE
Show where the dragged metadata is about to land

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#275]
It seems to end up on the one below quite often when I drag and drop! Indicating which it is currently hovering over with a dashed box, a shading, or something would be good.

**Comment by jonc125** [comment]
There's now a fix for this as part of #280 deployed on scrambler. See what you think!

**Comment by mirams** [comment]
Nice! Maybe going more bold rather than more faint would be even nicer?!

**Comment by jonc125** [comment]
How does it look now? (I've also added Michael's search box request.)

**Comment by mirams** [comment]
I love both features, nice tweaks that really improve the usability!
