### ISSUE TITLE
Simple list views of fitting results

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#276]
The simplest way to navigate to and view results of individual fitting experiments is just to list everything linked to a given model/protocol/dataset/fitting spec version.

There's commented out code in `entity_version.html` for a button that could link to such a view. Though the button text should probably read 'Fitting results'.

The view itself will be very similar to `entities/compare_experiments.html`, except that initially it won't have the comparison checkboxes, just the individual links. (Until the comparison views from #134 are done.)

- [x] List all fitting results for a given model version
    - Group the list by dataset
- [x] List all fitting results for a given dataset
    - Group the list by model
    - Have a button to show all versions or only the latest
- [x] List all fitting results for a given protocol
    - Group by dataset, subgroup by model
    - Have a button to show all model versions or only the latest
- [x] List all fitting results for a given fitting spec
    - Group by dataset, subgroup by model
    - Have a button to show all model versions or only the latest

Child of #135.

**Comment by helenst** [comment]
Should "List all fitting results for a given protocol" be "List all fitting results for a given protocol version" and similar for fitting spec, or is that intentionally different from model?

**Comment by jonc125** [comment]
Yes, those should be specific to a protocol/spec version, sorry!
