### ISSUE TITLE
UI to run a new fitting experiment

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#277]
Recall that a fitting spec is linked to a protocol (later maybe more than one) which is in turn linked to zero or more datasets.
To be able to run a fit we need to specify:
* Version of fitting spec
* Version of protocol
* Dataset
* Version of model

This view is reached initially via a button from viewing a single version of a fitting spec.
Later, via a button from a dataset (iff there is a fitting spec connected to a linked protocol) or model.

The view should have 4 drop-down menus in a row, to select Fitting spec, Protocol, Dataset, Model.
One of these will be pre-selected and unable to be changed, depending on how the view was reached.

Selecting options from each drop-down will constrain what options are offered in the others, with Javascript code updating the lists.
* Once a fitting spec is chosen, only linked protocols and datasets are available. Similarly if we start from a dataset.
* Initially all models are listed, but eventually these will be filtered to show only those with an interface compatible to the selected protocol & fitting spec (once this interface info is in the DB)

Under each of the top drop-downs with versions (i.e. not datasets) there should be a drop-down to select version, defaulting to the latest.
This should be greyed out until a selection is made in the upper row, and then filled in via an AJAX call with the available versions.

At the bottom there should be a button 'Fit model to data' which submits the fitting experiment to the queue.

The submission & result retrieval system will be very similar to that for normal experiments; common code should be extracted. See also #134.
See the `if protocol.is_fitting_spec` branch in `experiments/processing.py` for what needs to be sent to the back-end for a fitting experiment.
It might make sense to change `submit_experiment` so it takes `model_version` etc as a `CachedModelVersion`, drops the `model` & `protocol` arguments (since these can be found from the cached versions) and has optional `dataset` and `fitting_spec_version` arguments?

Child of #135.

Tasks:
- [x] Create basic view with form
- [x] Back end validation of valid entity / version combinations
- [x] Allow preselection of entities and versions on page load
- [x] Check user permissions on entities (preselected and submitted)
- [x] Check user permissions on ajax endpoint
- [x] Submit fitting experiment to back end
- [x] Simplify call signature for submission code
- [x] Javascript filtering of dropdown values
  - [x] Grey out versions until entity selected
  - [x] Ajax endpoint to provide valid values
- [x] Page and form styling
- [x] Buttons from entity pages
- [x] The JS action to re-run a fitting experiment doesn't work - it tries to do a normal experiment run, not a fitting experiment

**Comment by mirams** [comment]
Yeah, I was imagining that specifying a Dataset would automatically tell WL what Protocol was relevant, so user wouldn't have to link them at time of writing fitting spec, but at time of uploading data. 

Not sure how version control between Dataset and protocol should work though if you wanted to increment to one or the other, probably should be defined and fixed at time of Dataset upload I would think? And 'Add new version' for a dataset could upload new data OR update the protocol it was linked to (to either a new protocol or a new version of same protocol).

**Comment by helenst** [comment]
How should the page behave with regard to re-running experiments with same entities, versions etc? Should this be allowed? Or should it be as with the matrix and just take you straight through to the existing version that already ran?

**Comment by jonc125** [comment]
> Not sure how version control between Dataset and protocol should work though if you wanted to increment to one or the other, probably should be defined and fixed at time of Dataset upload I would think? And 'Add new version' for a dataset could upload new data OR update the protocol it was linked to (to either a new protocol or a new version of same protocol).

At present you can't have versions of a dataset, so new data => new dataset. Also a dataset can only be linked to one protocol, but we'll relax this and allow many-to-many later. So probably you could have a 'link protocol' button when viewing a dataset, and 'link dataset' when viewing a protocol. See #274.

**Comment by jonc125** [comment]
> How should the page behave with regard to re-running experiments with same entities, versions etc? Should this be allowed? Or should it be as with the matrix and just take you straight through to the existing version that already ran?

I think from this page it would run a new fitting experiment, so create you a new `FittingResultVersion`. Would you agree @mirams ?

**Comment by mirams** [comment]
Since there's stochasticity in the fitting algorithms then repeating the same fitting experiment makes sense and isn't redundant like it is for the deterministic model/protocol combinations.  So yeah, multiple runs of the same fitting spec want to be allowed and viewable (somehow! Would have to think about what the 'outputs' of a fit look like for comparing the results of them)
