### ISSUE TITLE
Matrix view for fitting experiments

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#278]
Similarly to the main experiments matrix, we want a matrix view for fitting experiments.

However, for this **each fitting spec has its own matrix**, with models on the rows, and dataset+protocol combinations as the columns. (If there is only one protocol for a given dataset, you don't need to display the protocol name at all.)

@mirams @MichaelClerx how should we handle versions of models & protocols here? In the main matrix you only see the latest (visible) version of each by default (and corresponding results). For fitting would it be better to include results from earlier versions if they exist but results for the latest version(s) don't? Similarly, should we include results generated from earlier versions of the fitting spec (if there aren't corresponding results from the latest version)?

Comparison mode should be supported as for the existing matrix, so you can select multiple rows/columns/squares and compare results, and also view a sub-matrix.

Clicking on a blank square should launch the 'run fitting' view from #277, with all drop-downs pre-filled (including versions).

I'm unsure yet how much we'll be able to share JS code from the existing matrix, and how much would need to be copy & tweak.

Child of #135. Do #276 and #277 first.

**Comment by MichaelClerx** [comment]
> @mirams @MichaelClerx how should we handle versions of models & protocols here? In the main matrix you only see the latest (visible) version of each by default (and corresponding results). For fitting would it be better to include results from earlier versions if they exist but results for the latest version(s) don't? Similarly, should we include results generated from earlier versions of the fitting spec (if there aren't corresponding results from the latest version)?

Not sure! I think it relates to this:

> Clicking on a blank square should launch the 'run fitting' view from #277, with all drop-downs pre-filled (including versions).

If we think seeing all the versions is important, then maybe we should let that go for fitting? Maybe clicking a square should take you to a page that shows either the most recent available results, or possibly an overview of all versions? Running could be a button on that page somewhere?

@mirams ?

**Comment by jonc125** [comment]
@mirams Helen is about to start work on this, so would value your opinion on what should be shown, if you have one!

**Comment by mirams** [comment]
I think you would still want a blank to show "the current version of the fitting spec hasn't been run on the current model/dataset"

**Comment by jonc125** [comment]
Gary:
> Does the usual model/protocol matrix let you get to old versions of the experiment on previous versions of the model/protocol, I don't think it does? Unless I can't hit on any that have been run on old ones...
> It would certainly be nice to be able to see a list of fitting results from previous versions of the model, dataset or fitting spec...

Jonathan:
> You can, but it’s a few clicks to get there. You can go to a model or protocol and select ‘Compare… Results from other versions’

Gary:
> Ah, OK, quite nice how that brings up a new matrix, I don't think I'd remembered it did that

Jonathan:
> It’s a new thing in WL2. There wasn’t really an easy way to do it at all in WL1, except for manually constructing URLs

Gary:
> A nice way to see such a thing for fitting specs would be nice, although I guess it becomes 3D (!) Maybe a drop down at the top with versions of the fitting spec?!

Jonathan:
> Hmm. Comparing different versions of a model or protocol could be done similarly to normal experiments. What would a matrix comparing different versions of a spec look like? Does it even make sense?
> Helen has implemented a simple list view to get to fitting results (and compare them) so you can see how different versions of a spec operate via that route, without showing a matrix

Gary:
> OK, that's probably OK for now. I think it will only make sense when we've thought about an example of a few different cells' worth of data, and a couple of models with the same fitting spec applied, and then with a slightly different fitting spec applied. You'd potentially want to compare all those fits and parameter values etc.
> Occurred to me that eventually* (not yet) you might want to generate your model (which appears in main model/protocol matrix with a fitting spec, in which case you wouldn't want to apply the fitting spec to the model it is an output of(!).

**Comment by mirams** [comment]
> Occurred to me that eventually* (not yet) you might want to generate your model (which appears in main model/protocol matrix with a fitting spec, in which case you wouldn't want to apply the fitting spec to the model it is an output of(!).

Relatedly, we have not really thought about showing the results of validation studies in this, which would be the second half of the fitting spec - running the fitted model through some other protocols and comparing to data not used in the fit.

**Comment by jonc125** [comment]
#314 is now deployed on scrambler ready for feedback @mirams @MichaelClerx . See e.g. https://scrambler.cs.ox.ac.uk/fitting/specs/537/results/models/63 which shows fitting results for the main spec currently in the system.

Some things I've noticed while setting up the initial runs:

* From https://scrambler.cs.ox.ac.uk/entities/models/63/versions/v1/fittings 
    * [ ] The fittings page from a model shouldn’t show ‘view as matrix’ (yet) as it isn't implemented. Would we like a matrix view of all fitting results for a given model, as well as for a given spec?
    * [ ] This view should show fitting spec name as well as the protocol, or you can't tell the difference between the two items listed for cell 5
* From https://scrambler.cs.ox.ac.uk/fitting/specs/537/results?
    * [ ] The default moderated view shows nothing as the dataset isn’t moderated. At present we can't change a dataset's visibility, which needs to be fixed, possibly after #195 which should make it easier to do.
