### ISSUE TITLE
Implement basic viewer plugins for entity views

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#28]
Building on #21.

- [x] Display content, e.g. [here](https://travis.cs.ox.ac.uk/FunctionalCuration/model/BeelerReuter1977/4/v3syc/151/beeler_reuter_model_1977cellml/108910/displayContent).
- [x] Download, e.g. [here](https://travis.cs.ox.ac.uk/FunctionalCuration/download/m/v3qx3/151/108910/beeler_reuter_model_1977cellml) - I'd be tempted to rename this to download rather than save, and use a more typical download icon.

I suspect this mainly requires updating the existing Javascript viewers, but there will probably need to be a REST endpoint adding to get a file's contents. @helenst can you advise on that aspect?

**Comment by MichaelClerx** [comment]
This sounds cool! Esp. if nice and extensible :-)

**Comment by helenst** [comment]
Work on this is pretty much complete on the `entity-viewers` branch. It's based on the branch for #58 since it builds on part of that code- will rebase and submit PR after that one's in.
