### ISSUE TITLE
Main nav bar redesign

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#292]
@MichaelClerx suggested this as part of #262, since that needs to add an item. Similarly we need to add an item for #135 and related issues.

Currently the nav bar has:
* For an anonymous user:
    - Home, Experiments, About, Log in, Register
* For a logged-in user:
    - Home, Experiments, My models, My protocol, My datasets, Username
    - Username menu has: My files, Tasks, Account, (Admin), Log out

The anonymous version would remain the same, except that it would add a Stories link as part of #262.

The logged-in version should become:
- Home, Experiments, Fitting results, My files, Username
- 'My files' should be a drop-down like the username menu, with options: Models, Datasets, Protocols, Fitting specifications

'My files' can then be removed from the username menu.

This should probably be done as part of #276.

**Comment by helenst** [comment]
Should the anonymous version have Fitting Results too?

**Comment by jonc125** [comment]
Eventually I think it would. Although actually at the moment we have no view for that, since the results list is always linked to an existing model/protocol/spec/dataset and is accessed via that. Whether for logged-in or anonymous users. So perhaps that item shouldn't exist for any kind of user?

**Comment by helenst** [comment]
I was thinking it could link to the `?show_fits=true` version of the experiments matrix for now and then to the new fitting results matrix view once we have it. But can remove it entirely for now if you prefer.

**Comment by jonc125** [comment]
That `show_fits` thing was just a hack because we didn't have fitting in properly but were pretending they were normal experiments. So once #300 is merged we can actually get rid of it! (And the rest of the hacky implementation of fitting.)

**Comment by helenst** [comment]
I'll take it out for now. Maybe can be added back into the menu after #278 adds a proper matrix view?
