### ISSUE TITLE
Find/create Python combine archive tool

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#30]
Requirements:

- Reading
- Writing
- Extensible with our own combine format variations

See #23 

Step 1: Evaluate https://github.com/FreakyBytes/pyCombineArchive

**Comment by jonc125** [comment]
Thoughts on https://github.com/FreakyBytes/pyCombineArchive :
* Basically a one-person show from the Rostock group
* Does have tests, using unittest
* Uses a custom zipfile module to support deleting files from archives
* Isn't on PyPI
* Is described as very beta, "would not recommend to use this library for anything else than testing"
* BSD 3-clause licence
* Python 2 only
* Conclusion: would need lots of work to adopt and rework to be useful to the community

**Comment by jonc125** [comment]
[Tellurium](http://tellurium.readthedocs.io) uses the Python bindings to libCombine, available as [tecombine](https://pypi.python.org/pypi/tecombine) (0.2.2.1) and python-libcombine (0.2.1) from PyPI.
* Uses libSBML's XML parsing & SWIG: quite bulky!
* Bigger community and potential developer pool; Frank is good and responsive
* BSD 2-clause licence
* Slightly confusing packaging with 2 names at different versions! tecombine has wheels but seems to be deprecated? python-libcombine doesn't have wheels and is a lower version!
* There are [Python examples](https://github.com/sbmlteam/libCombine/tree/master/examples/python) used as (manual) tests; no CI
* There is [API documentation](https://sbmlteam.github.io/libCombine/html/class_combine_archive.html)
* Conclusion: not ideal, but probably a better option!

**Comment by jonc125** [comment]
[pysces](https://github.com/PySCeS/pysces/blob/57a2c76eb27c1afabc3bfd0f3249cd7d817ddb7c/pysces/PyscesSED.py) just has custom write code.

The Physiome Model Repository has an [OMEX interface](https://github.com/PMR2/pmr2.omex), but it's tightly coupled to the PMR2 codebase.

**Comment by jonc125** [comment]
Have also asked at https://groups.google.com/forum/?hl=en-GB#!topic/combine-archive/oRQCoZfUblY

**Comment by MichaelClerx** [comment]
Can't be that hard to build can it?
I generate zip files in myokit all the time with no dependencies beyond python's standard library

**Comment by jonc125** [comment]
There are responses from the main library developers in the thread linked above now. As Michael says, a pure Python library for the functionality we actually need would probably be easy to write, but it might make sense to start with libCombine so we're being 'good citizens'! It did pip install for me, even if there weren't wheels available.

**Comment by MichaelClerx** [comment]
It does depend on libSBML though, bit overkill?

**Comment by jonc125** [comment]
Indeed, that is the downside! But if its API isn't too bad we can start there to get something running and switch to a light-weight Python alternative later.

**Comment by jonc125** [comment]
Had issues getting libCOMBINE to work in #47, so Helen has written our own thing for just what we need for now.

**Comment by jonc125** [comment]
Closing for now since we implement features we need as required. Can revisit if we decide to create a standalone library with others (e.g. PMR).
