### ISSUE TITLE
Remove hacky fitting spec implementation from front-end

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#315]
Once #314 merged and deployed, and key fitting results from old implementation replicated in the new one.

@mirams is it just the single Kylie sine wave fit to cell 5 we care about? Or are there others I should run?

**Comment by mirams** [comment]
Once that's working I think it's OK, when the fitting spec is up and running we can try that with other datasets. Or are there specific things you'd like to test - like different length datasets or different protocols or anything? We can easily make some synthetic data to try other cases even if we don't have real stuff
