### ISSUE TITLE
Everything clickable should be a proper link

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#32]
In the current web lab we can't do Ctrl-Click on the squares in the matrix to open the result in a new tab, this should be changed in the new version (this was making Chon's life difficult last week)

**Comment by jonc125** [comment]
The tricky bit about this is that the behaviour needs to be different in comparison mode, where it isn't a link! So I think the comparison mode button would need to alter the HTML & JS event handlers on each box.

For some buttons they don't actually change view (e.g. the comparison mode button). But for ones that are link-like it might make sense to make it possible to open in new tab. This ties in with making sure everything that changes 'view' within JS changes the page URL (e.g. setting a `#blah` component) so you can actually navigate directly to the view. (Some already do this, e.g. the public expt list buttons. The main ones that don't are those on the model/protocol view.)

**Comment by MichaelClerx** [comment]
Out of interest: How are we doing js/ajax things? Is there a general framework to do interactive UI things within django that we need to use? @helenst ?

**Comment by helenst** [comment]
At the moment, the js/ajax is raw js with jquery, no particular framework. I'm trying not to touch the js code more than I have to. although in keeping with the theme of this ticket, the old site has bits that are more js based and don't need to be - and it doesn't necessarily make sense to keep that way in Django. So I'm trying to convert things to proper pages / clickable links where possible. I've already done this with parts of the login system, and will continue trying to take a sensible approach with that.

If we wanted to take a more structured, frameworked approach to the front end that could be backed by Django Rest Framework serving up json data, but Django doesn't provide the UI framework which would consume that data, and it doesn't really mind which one is chosen (Angular, Ember, React or others)

**Comment by MichaelClerx** [comment]
Thanks! That all sounds very good.

I spent about 6 months last year working as a React developer, which was fun but seems like overkill for the web lab! Looking at angular and ember, it's not immediately clear to me how we'd use this in the web lab. From the demos it looks like we'd do the entire front-end in one of these JS frameworks and then use django only to provide an API to access data/logic?

I'd thought the web lab could be a bit less JS-heavy than that? Very curious to hear your thoughts

**Comment by jonc125** [comment]
Certainly for something like Angular (which we're trying to use for other projects within the team) you need to do the whole front-end using it really, and it'd be a big effort to move over. I've not used Ember but get the impression it'd be similar. @klapaukh was going to look at moving piecemeal over to TypeScript where we need to update particular parts of the JS code, which gets us a bit more modern & maintainable. But for the most part I think sticking to things like jQuery is probably the right level of abstraction for us. We can still use the Django REST framework to define API endpoints that our existing JS code calls.
