### ISSUE TITLE
Metadata annotation editor isn't showing existing tags as shaded any more

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#338]
The metadata annotation tool used to show shaded things for any already-tagged metadata. It doesn't any more, e.g. [Luo-Rudy 1991](https://scrambler.cs.ox.ac.uk/entities/models/3/versions/785d581c1eb54f0bba52daeeaa10adeefe94c479/luo_rudy_1991.cellml/editMetadata)

which looks like this:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/858776/113164287-e273dd00-9238-11eb-9461-add13a66bc45.png">

when you add some new metadata it shades in the right hand entries...

**Comment by mirams** [comment]
See also #344 if you are working on this!

**Comment by jonc125** [comment]
I've just looked at LR91 on scrambler and it *is* showing up already shaded on the right hand side, even before I've annotated anything...

**Comment by mirams** [comment]
using that link above? What browser are you using!?

**Comment by mirams** [comment]
Oh great, it works on Safari and Chrome but not Firefox (it definitely used to work on Firefox!)

**Comment by jonc125** [comment]
Oh good grief! That's a bit insane. OK, I'll see what I can spot...

**Comment by mirams** [comment]
Now I am completely confused, I have it reproducibly not showing for Beeler-Reuter on Chrome, but showing for LuoRudy91 both once logged in. There's something very odd going on. Don't suppose you can shed any light when you also spotted this @MichaelClerx in that #268 ticket?

**Comment by jonc125** [comment]
Aha, figured out what's going on from the web dev console. The annotator needs to load various bits of information.

If the loads happen in the order Ontology -> Model -> Interfaces -> Custom annotations, you don't get the shading.

If the loads happen in the order Ontology -> Interfaces -> Custom annotations -> Model, you *do* get the shading.

Hence the random results, as the order is timing sensitive depending on how fast the GET requests to the server take. This should give me a starting point to make this robust tomorrow, if I have time!

**Comment by mirams** [comment]
Great work, thought I was going a bit mad there for a while!
