### ISSUE TITLE
Basic stimulus metadata missing from annotation tool

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#344]
Just tried to annotate a fairly 'clean' model with basic metadata. Couldn't find the basic stimulus metadata in the list any more, and indeed when filtering on 1Hz pacing it doesn't appear, but is required:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/858776/118048590-64950c80-b374-11eb-9d28-0df270610f96.png">

**Comment by mirams** [comment]
I will take the 'confused' emoji as an acknowledgement of the problem Jon! ;-)

**Comment by mirams** [comment]
See also #338...

**Comment by jonc125** [comment]
Will be closed by https://github.com/ModellingWebLab/ontologies/pull/8 once deployed on scrambler.
