### ISSUE TITLE
WL Stories: Toggle options 

### ISSUE THREAD

**Issue by agrawal-aditi** [ModellingWebLab/WebLab#413]
Toggle options for model groups show up even outside a story.
See the image below of a comparison of hERG models: https://tinyurl.com/3t6vcy96 
![private_groups_toggle](https://user-images.githubusercontent.com/56925503/165943314-1cea0cca-4622-439e-abe1-7b2d6621d2dd.png)

The following would be useful features:
1. Restricting the model groups to only the strories
2. The ability to select which model groups are needed in any story

**Comment by MauriceHendrix** [comment]
The problem really now is that I'm not sure what the desired behaviour is anymore. when I spoke to @mirams before my holiday we conclused that it wasn't clean and needed thinking about.

The way I see it, you either 
- get all groups that relate to a graph and get them everywhere the graph appears, possibly with the exclusion of private groups.
- or you need to specify together with the graph in a story which of the groups you want to show and then show only those (and don't show groups elsewhere where the graph appears). This of course increases the complexity of specifying a story further.

let me know what you think @agrawal-aditi  @MichaelClerx  @mirams 
also related:  #410 #412

**Comment by MichaelClerx** [comment]
If we think big, eventually there should be loads of groups, made by lots of different people (and reflecting lots of different opinions).
In that case, you wouldn't want to show all groups on every multi-model graph, but just a restricted set (moderated groups?)
For stories, you'd want to specify the groups relevant to your story (which unfortunately makes stories a bit more complex to set up, yes)

**Comment by mirams** [comment]
I think the groups probably don't want to show up everywhere, agree that there will eventually be loads of groups for anyone interested in looking at batches of models that will quickly get unwieldy to show on every graph. And in Aditi's example above, there are plenty where the categories are ICaL-related and irrelevant (or even misleading) for hERG (e.g. groups to do with calcium channel properties won't even be used in an IKr-only experiment).

So it probably would mean restricting them to stories for now, and then selecting a bunch - probably most usefully various groups (more than one allowed) for a given graph in a story.

**Comment by MauriceHendrix** [comment]
actually...
the way we're picking a graph now we're already specifying a group (or a single model).

![image](https://user-images.githubusercontent.com/52317399/169274249-5606474b-1c29-48a3-bec9-b5d34455eb82.png)

Would it make more sense to make this a multi-select? Or would it make more sense to have 2 seperate selectors: one for the models that are in the graph and one for the gtoup toggles? @mirams @agrawal-aditi  @MichaelClerx

**Comment by MauriceHendrix** [comment]
more along these lines @mirams ?
![image](https://user-images.githubusercontent.com/52317399/169311507-8af8b2d2-577b-4b57-a890-2af5b1eda00d.png)

**Comment by mirams** [comment]
I guess for convenience you might want to select all models at the top from group(s) too, with something like the existing menu but allowing multiple selections, i.e. "Select Model(s) or Model Group(s) shown in graph".

I think the available toggles probably makes sense - so you can define what is interesting on a case-by-case basis (e.g. just include gating type, or species or cell type or whatever). Makes it a bit harder for someone to do a new comparison you hadn't thought of, but without overwhelming them with all possible options, I can't see an easy way to do that. What do you think @agrawal-aditi @MichaelClerx ?

**Comment by agrawal-aditi** [comment]
I agree that the existing toggle options make sense for the purpose of selecting what models should go in -> someone may only want to study a group that is already defined and has say 40 models. So it would be inconvenient to select all 40 of those models individually. -> So existing way of selecting models/groups of models is pretty good.

At this point I'd like to clarify that model group may mean different things to us:
1. All the models that have a certain characteristic-> say being derived from canine cells: so this refers to the modelsss
2. The tag that is assigned to a single model -> say model OHara has been tagged to be a ventricular cell model -> I will call this model tag/toggle

What is needed is something like the bottom panel in the mockup Maurice has shown where you can select which toggle should appear in the story (ie which tag associated with a model should show up for a story can be defined by the user)

**Comment by agrawal-aditi** [comment]
yes! I probably shouldn't have used the term tag
But I think I am on the same page as you, just that the in the mockup shown above we shouldn't remove the ability to select entire model groups in the top panel (where it says-> available models)

**Comment by MauriceHendrix** [comment]
> yes! I probably shouldn't have used the term tag But I think I am on the same page as you, just that the in the mockup shown above we shouldn't remove the ability to select entire model groups in the top panel (where it says-> available models)

aah i get it I didn't mean to remove groups from that, that was just a slightly lazy copy-paste

**Comment by MauriceHendrix** [comment]
ok I get it now ... it's going to be a pretty big change I think
