### ISSUE TITLE
Ensure simultaneous attempts at updating entities are handled gracefully

### ISSUE THREAD

**Issue by helenst** [ModellingWebLab/WebLab#45]
Following on from work in #21 and #44, ensure that if users A and B are attempting to modify the same entity, the two modifications do not interfere with one another.

This should probably involve presenting user B with an error message on the new version form, indicating that the entity was updated by user A since they loaded the page. Invite them to try again, applying their changes on top of user A's version.

Dealing with any kind of merge or conflict resolution could get fiddly from a UI perspective, so probably best to keep it simple for now and just prevent the repo getting into a bad state, warning the user so they can try again.

**Comment by jonc125** [comment]
So we should include a hidden field on the new version form containing the parent commit SHA?

**Comment by helenst** [comment]
Seems like a sensible way of doing things for now
