### ISSUE TITLE
Implement protocol file syntax checking

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#48]
This is also where the protocol interface gets stored within the DB. (Or in the future, in an RDF store.)

With additional features from the original:
* Create an error.txt file for any problems seen (the original does this too)
* Generate the readme.md as part of this step? (See also #75)
* Report in error.txt if there is no master file marked

We'll need to think about the most appropriate way of adding the error.txt file. Probably we have to create a new commit in the repository, and maybe move any tags? Or should it be a more ephemeral 'file' associated with the version only in our cache - since you wouldn't want it hanging around in a subsequent updated version!

**Comment by jonc125** [comment]
@helenst I hope to have a bit of time to start on this next week. Do my ideas about making these ephemeral files in the repocache seem like a sensible first approach to try?

**Comment by helenst** [comment]
We'd need to be careful about the cache repopulation script - currently it wipes everything from the cache and regenerates from scratch. Depending on whether that's actually being run (it shouldn't need to be). So if the repocache is the only place this file lives, it could be lost that way. 

One other possibility might be to store it as a git note?

**Comment by jonc125** [comment]
Indeed, I'm thinking using a note with repocache for speed is probably the way to go. Will have a play in that direction :)
