### ISSUE TITLE
Running experiments with non-public entities is broken

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#55]
The last part of #15 left over from #51.

Running experiments with non-public entities is broken - when the runner tries to get the entity archive, it's redirected to the login page...

@helenst Could we do something like pass to the runner service (e.g. as part of the signature) a token which it could pass as part of get requests to log in automatically as a special user with read-only permission on every entity? Would this approach also secure the callback handler sufficiently?

**Comment by helenst** [comment]
@jonc125 That sounds fine to me. The callback handler could check the passed in key and allow bypassing the visibility settings if it matches. The key can be randomly generated and attached to experiment version so it's different on each run. We can check that entity links up with experiment version and that the relevant experiment is currently queued or running (presumably no reason to access once it's complete?), so that at least limits the scope of unwanted access.

**Comment by jonc125** [comment]
Yes, this would only be relevant for queued/running experiments. Does it make more sense to have the key as an indexed column on ExperimentVersion, or in its own table with the link to experiment version as a foreign key? If the latter, checking for a valid key would stay very quick as we can delete rows from the table when experiments complete, avoiding having to check the status column.

The key could then just **be** the signature passed to the runner - no need for the runner to know the ExperimentVersion id - which saves having to change the existing runner code to make this work.

Possibly the task_id could move to the new table as well actually, since that's also only relevant while the experiment is running? And call the table RunningExperiments?

**Comment by helenst** [comment]
If it's OK and relatively easy to make that change to the runner, that's probably best. Otherwise, we can accept it as a GET param and include that in the model/protocol URL passed in on experiment submission, that shouldn't require any change in the runner.

**Comment by jonc125** [comment]
That's easy for me to change, so just let me know what you'd like it to look like and I'll do it.

**Comment by jonc125** [comment]
Fixed by #56.
