### ISSUE TITLE
Set up login system

### ISSUE THREAD

**Issue by helenst** [ModellingWebLab/WebLab#6]
Make sure users can:
- [x] Register
- [x] Log in
- [x] Reset password
- [x] Change password
- [x] View account details
- [x] Log in with GitHub
- [x] Log in with Google

Also:
- [x] add email flag
- [x] email admins when new user registers
- [x] icons / visuals for oauth logins: display on registration page too
- [x] edit email address if registered locally only (no oauth)
- [x] Change password could be a button
- [x] Get rid of username field and just use email address to identify

The Django system provides a lot of help with these features, but templates and URL config will still need to be provided, as well as setting up a suitable user model.

**Comment by jonc125** [comment]
How easy is it to add OAuth authentication (via e.g. GitHub and/or Google)? @mirams requested this earlier today, to avoid needing another password!

**Comment by helenst** [comment]
@jonc125 https://github.com/python-social-auth should help with this... it's the same thing UCL Dashboard uses (it can be configured to authenticate rather than just connect to existing account)

**Comment by jonc125** [comment]
That would be nice to have as an option then, if it's not much work. How long do you think it would take?

Also, is it possible for site admins to be sent an email when a user registers?

**Comment by helenst** [comment]
@jonc125 Shouldn't be a lot of work. At a guess, half a day, max 1 day.

Sending an email should be no problem.

**Comment by jonc125** [comment]
@helenst Great, could you include that feature then please!
