### ISSUE TITLE
Implement extra custom experiment matrix views

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#64]
Replicate the WL1 buttons at the top of the matrix view for logged-in users, i.e.
* Show just moderated / all public / all visible-to-me / my experiments
* Extra buttons to hide moderated models / protocols from views that include these among others (all the above views include moderated entities by default)

The default view for anonymous users should be moderated experiments (which requires #41 & requires #40). The default for for logged-in users is 'my experiments' (which includes moderated ones as well by default).

**Comment by helenst** [comment]
Tasks:

- [ ] Add "mine" filter to matrix json view
- [ ] Add "public" filter to matrix json view
- [ ] Add moderator visibility status
- [ ] Add "moderated" filter to matrix json
- [ ] Add moderator capability to users
- [ ] Ensure correct display of visibility dropdown depending on user moderator status
- [ ] Add hide/display moderated entities filter logic into matrix json view
- [ ] Add front end buttons and hook up to back end logic

**Comment by jonc125** [comment]
Outstanding tasks not covered by #120:
- [ ] Correctly handle multiple versions with varying visibilities (see also #73)
- [ ] Set default view for logged-in users to 'my experiments'
