### ISSUE TITLE
Add view to run experiments based on a given entity version

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#67]
This is the 'Run experiments' button on an entity version view in WL1, e.g. https://travis.cs.ox.ac.uk/FunctionalCuration/batch/model/v9zjy/555. The corresponding JSP is https://github.com/ModellingWebLab/fcweb/blob/master/src/main/webapp/WEB-INF/Batch.jsp, which would need converting to a Django template. It uses some [Javascript code](https://github.com/ModellingWebLab/fcweb/blob/master/src/main/webapp/res/js/batch.js) for selecting/deselecting checkboxes and submitting the callback, but using jQuery properly the selection bit could be done in only a few lines! And the Django-y approach to submission would be an HTTP post rather than JS callback.

On submission we'd need to do something a bit like part of `entities.views.EntityNewVersionView` - record experiments to be run in the `PlannedExperiments` table (done by the `record_experiments_to_run` function there; logic would be slightly different here) and then either show the 'run experiments' page again or redirect to the entities:version page. I'm guessing the latter would be better.

We perhaps want to extend it by adding some filters to show _only_ my/my+moderated/my+public entities? Probably not for this issue though!

Low priority since you can run experiments via the matrix, it's just not as convenient for bulk operations, e.g. to easily re-run experiments when uploading a new entity version.

**Comment by jonc125** [comment]
@mirams do you think this is needed by June?

**Comment by mirams** [comment]
It's pretty handy, you can only run on the most recent version of things in the matrix view I suppose, which is probably OK for most users (although annoying and slower at the moment to load), but hardcore users might want to try old version of model with different protocols and stuff?
