### ISSUE TITLE
Achieve WL1 parity

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#68]
At least for features we still care about, so we can move all entities over and turn off the old WL1 (perhaps after a period where it's read-only - what do you reckon @MichaelClerx @mirams ?).

Features needed in approximate priority order:
- Parent of #28
- Parent of #41
- Parent of #40
- Parent of #26
- Parent of #65
- Parent of #66
- Parent of #63
- Parent of #64
- Parent of #42

Optional features (that we could perhaps live without initially?):
- Parent of #39
- Parent of #67
- Parent of #48

**Comment by jonc125** [comment]
All issues linked to this have now been closed!

**Comment by mirams** [comment]
Does that mean we should be migrating over to the new server and retiring travis' web lab (Fergus wants to upgrade the machine)?

**Comment by jonc125** [comment]
Yes, we should plan for that. I need to merge another PR and deploy on scrambler, then double-check it's happy, but at that point we (you?) should probably reach out to known users and ask them to try it out.
