### ISSUE TITLE
Don't make notes/error messages push page content down

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#70]
This is particularly annoying for the matrix page: if you try and click across a row to start some experiments it shifts the matrix down and messes up the mouse clicking!

Options are:
1. Put the box at the bottom of the page content. Possibly not ideal as people might not notice it!
1. Make the box sit on top of the page content, so it doesn't move it, but still at the top. You could still get issues if the box gets so big it covers the part you're clicking on, so maybe it should have a maximum size with a 'show all' button as well as the 'dismiss' link?

Have you a preference @mirams ?

**Comment by mirams** [comment]
I was imagining 2) with it sitting/floating on top of the page, starting where it already does (possibly a little bit transparent to make it obvious it is doing that). Could live with dismissing it once it gets too big!
