### ISSUE TITLE
Review speed of experiments matrix view

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#73]
As we get more experiments on scrambler, we should check it's presenting the matrix at least as quickly as WL1 could.

Child of #68.

**Comment by jonc125** [comment]
And indeed it's now falling over entirely due to `OSError: [Errno 24] Too many open files` - see https://rollbar.com/jonc125/Web-Lab/items/9/

**Comment by jonc125** [comment]
Looks like there are known issues here: https://gitpython.readthedocs.io/en/stable/intro.html#leakage-of-system-resources

**Comment by MichaelClerx** [comment]
That's disappointing! Wonder why they put up a message apologising for the bug instead of fixing it...

**Comment by MichaelClerx** [comment]
Not entirely sure what they're talking about. This offers some hints: https://stackoverflow.com/questions/14628486/why-arent-destructors-guaranteed-to-be-called-on-interpreter-exit

**Comment by mirams** [comment]
This is really slow - just timed (when logged in as myself, in case that matters):
on `scrambler` web lab it takes 18 seconds from pressing the 'Experiment' tab to seeing the matrix, on the old `travis` it takes less than 1 second.

**Comment by mirams** [comment]
Dropped down to no use, and still takes about 4 seconds rather than less than 1 :-(

**Comment by jonc125** [comment]
Currently we have nearly 7s for the public view:
```
May 09 12:04:46 scrambler weblab[11258]: [pid: 11365|app: 0|req: 9/14] 128.40.131.160 () {50 vars in 1096 bytes} [Thu May  9 11:04:39 2019] GET /experiments/matrix?subset=public => generated 655315 bytes in 6864 msecs (HTTP/2.0 200) 3 headers in 104 bytes (5 switches on core 0)
```

**Comment by jonc125** [comment]
On my local deploy, with fewer experiments, 1637 msecs:
```
May 09 11:20:14 weblab weblab[357]: [pid: 382|app: 0|req: 5/6] 10.0.2.2 () {46 vars in 1050 bytes} [Thu May  9 11:20:12 2019] GET /experiments/matrix?subset=mine => generated 13451 bytes in 1637 msecs (HTTP/1.1 200) 4 headers in 117 bytes (1 switches on core 0)
```
So still slow enough to see improvements! To produce this it does 109 SELECT queries and 10 calls to the git executable...

**Comment by jonc125** [comment]
With 62f6c777bcb09152ff9721b6ac938ee68c4b5eca we get 615 msecs, no calls to git, but still far too many SELECT queries.

**Comment by jonc125** [comment]
The latest locally has `generated 14188 bytes in 424 msecs`, with <10 queries. Will deploy on scrambler now to check there.

**Comment by jonc125** [comment]
On scrambler: `GET /experiments/matrix?subset=moderated => generated 660601 bytes in 443 msecs`!
