### ISSUE TITLE
Check WL1 workshop tasks work in WL2

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#74]
See https://docs.google.com/document/d/1iQPqYKBS-LPdqSddhSga_4mlbPbfIXZ_1LrzJ9kfOOs/edit for the practicals.

Web Lab 2 is https://scrambler.cs.ox.ac.uk/

The workshop materials (including slides & videos) are at https://chaste.cs.ox.ac.uk/trac/wiki/FunctionalCuration/Workshop2015

We *don't* need to check the 'Developing your own protocol descriptions' section, as this has been done by running lots of existing protocols on WL2! The 'Uploading your own models for analysis' section should also work, but worth double-checking the model annotation interface.

Child of #68. Requires #68.

**Comment by jonc125** [comment]
@mirams do you think it makes most sense for you to work on this, or shall I get one of my new people to do it as a learning exercise?

**Comment by mirams** [comment]
I think learning exercise! Little note for us to inform Fergus when we are ready to migrate the 'live' WL instance to WL2 on scrambler so he can upgrade travis.

**Comment by jonc125** [comment]
@d20gdx some useful background reading for this would be chapter 2 of my DPhil thesis (https://ora.ox.ac.uk/objects/uuid:24b96d62-b47c-458d-9dff-79b27dbdc9f2) which introduces cardiac modelling from a computer scientist's perspective.

**Comment by jonc125** [comment]
> Little note for us to inform Fergus when we have migrated the 'live' WL instance to WL2 on scrambler so he can upgrade travis.

I've added a note about this to https://github.com/ModellingWebLab/project_issues/issues/56

**Comment by d20gdx** [comment]
I have noticed that clicking on the link for the ICaL block protocol results in errors on scramber but not travis

**Comment by jonc125** [comment]
> I have noticed that clicking on the link for the ICaL block protocol results in errors on scramber but not travis

As in there's an errors.txt file shown? Indeed, that shouldn't be there! I'll investigate...

**Comment by jonc125** [comment]
Looks like a temporary glitch with the back-end parsing when the protocol was originally added or checked. Have just created a new protocol with the same files and it's fine. Rather than doing that for every protocol, we should probably just force a re-check of everything. I should be able to do that with a bit of low-level poking on the server later.

**Comment by jonc125** [comment]
For future reference, I'm using the following in the Django shell to remove existing error files:
```python
>>> from entities.models import ProtocolEntity
>>> for p in ProtocolEntity.objects.all():
...   for c in p.repo.commits:
...     if 'errors.txt' in c.ephemeral_file_names:
...       cache = p.repocache.get_version(c.hexsha)
...       iface = cache.interface.all()
...       iface.delete()
...       cmd = c._repo._repo.git
...       cmd.notes('--ref', c.FILE_LIST_REF, 'remove', c.hexsha)
```
And then
```bash
./manage.py analyse_entity_versions --settings config.settings.deployed
```

**Comment by sroderick-g5sro** [comment]
I have worked through the workshop steps and everything appears to be compatible with the new version of WebLab
