### ISSUE TITLE
Extract documentation from protocols as README.md

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#75]
When a new protocol (version) is uploaded, the `documentation {}` block should be parsed out and used to create a README.md file within the repo, but only if a README.md file doesn't already exist.

This will also need to be done as a one-off batch migration operation for existing protocols.

#48 suggests doing this as part of the protocol file syntax checking - so the backend (which needs to parse the protocol anyway) can extract the block and return it. But really you don't want to create a new version for this, you want it as part of the initial upload version. So I think it needs to be done here. Or you need to create an ephemeral file-like object as suggested for the `errors.txt` file.

Child of #68.

**Comment by jonc125** [comment]
I now think this would be best as a first test case of the ephemeral file support as discussed in #48.

**Comment by mirams** [comment]
> When a new protocol (version) is uploaded, the documentation {} block should be parsed out and used to create a README.md file within the repo, but only if a README.md file doesn't already exist.

And to update an existing README.md file if something has changed in the documentation block?

**Comment by jonc125** [comment]
> And to update an existing README.md file if something has changed in the documentation block?

Yes, providing that existing readme was created through this process. If there is a real file within the commit called README.md it won't be overwritten.

(Technically, the readme created through this process is ephemeral, and doesn't live within the commit, but in a git note referencing the commit.)
