### ISSUE TITLE
Improve git performance with caching

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#81]
Child of #68, following on from #76. Comments from there:

Me: We may wish to think about caching some bits of git metadata within the DB for speed - perhaps in a later phase once features for #68 are done. I'm thinking the list of commit SHAs and tags, perhaps also visibility stuff for #41 ? Provided all updates to the local repos on the server are mediated through Django (i.e. we don't allow direct push) it should be possible to keep things in sync, and we could have a cron job that re-syncs just in case.

Helen: Great! These changes to the repo lookups give significant performance improvements on that page. I've added a little further optimization to reduce the query count from the json view, but latest commit lookups on entities seem to be the next bottleneck to tackle. Caching these seems like a good idea - I think direct push could still be possible if we have some kind of process watching the filesystem for changes, but I'm guessing not a high priority at this stage.

**Comment by jonc125** [comment]
@helenst possibly add a list of things to cache in a comment here that we can refine?

**Comment by jonc125** [comment]
For instance, I think we want to cache all the commit SHAs & tags (not just the latest commit) and their visibility settings. Not sure if there's anything else.

**Comment by helenst** [comment]
I think those three are the main things to cache.

I have other possibilities in mind - e.g. with this caching strategy, loading up the matrix will still need to hit the cache at least once for each experiment to determine which which are visible. It might be desirable to improve on this by, for example, caching lists of experiment or entity IDs which have public or restricted visibility - this can then be combined with author info to quickly build up lists of entities / experiments visible to a given user. However, caching data about individual entities would be a good start - it should improve matrix speed again and will also be useful in other parts of the system.

Another possibility is to make the cached data queryable - e.g. one or more database tables dedicated to cached repository data - I'd be tempted to create a separate django app for doing so, to reinforce the distinction between regular data and cached data that's not "owned" by the db.

**Comment by jonc125** [comment]
Yes, I was envisaging the cache living in the DB. Having it as a separate app does make sense.
